apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: "organize-ai-server"
  labels:
    cloud.googleapis.com/location: "southamerica-east1"
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/description: sample tutorial service
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/container-dependencies: '{"nginx":["php-fpm"]}'
        revision-timestamp: "{{timestamp}}"
    spec:
      containerConcurrency: 1
      containers:
        - name: nginx
          image: "southamerica-east1-docker.pkg.dev/organize-ai-app/default/nginx:latest"
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256M
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
        - name: php-fpm
          image: "southamerica-east1-docker.pkg.dev/organize-ai-app/default/php-fpm:latest"
          env:
            - name: PORT
              value: "9000"
          resources:
            limits:
              cpu: 1000m
              memory: 335M
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 9000
# [END cloudrun_mc_hello_php_nginx_mc]
