name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker ${REGISTRY}
        env:
          REGISTRY: "${{ secrets.GCP_REGION }}-docker.pkg.dev"

      - name: Build Image on Artifact Registry
        run: |
          gcloud builds submit --tag=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPO_NAME }}/laravel:${{ github.sha }} .

      - name: Update migrate job
        run: |
          gcloud run jobs update migrate --image ${REGISTRY_NAME}/laravel --region ${REGION}

      - name: Execute Cloud Run Migrations Job
        run: |
          gcloud run jobs execute migrate --region ${{secrets.GCP_REGION}} --wait

      - name: Deploy to Cloud Run
        run: |
          gcloud run services update laravel \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPO_NAME }}/laravel:${{ github.sha }} \
            --region ${{secrets.GCP_REGION}} \
            --quiet
