name: Fix Code Style

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Check if Commit is Automated
      - name: Check Commit Message
        id: check_commit
        run: |
          echo "COMMIT_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.head_commit.message }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          if [[ "${GITHUB_ENV}" == *"Fixes coding style"* ]]; then
            echo "This is an automated commit. Skipping code style fixes."
            exit 0
          fi

      # Step 3: Set Up PHP Environment
      - name: Setup PHP
        if: "!contains(github.event.head_commit.message, 'Fixes coding style')"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none
          tools: composer

      # Step 4: Install Composer Dependencies
      - name: Install Composer Dependencies
        if: "!contains(github.event.head_commit.message, 'Fixes coding style')"
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      # Step 5: Install Laravel Pint Globally
      - name: Install Laravel Pint
        if: "!contains(github.event.head_commit.message, 'Fixes coding style')"
        run: composer global require laravel/pint

      # Step 6: Add Composer Global Bin to PATH
      - name: Add Composer Global Bin to PATH
        if: "!contains(github.event.head_commit.message, 'Fixes coding style')"
        run: echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      # Step 7: Run Laravel Pint to Fix Code Style
      - name: Run Laravel Pint
        if: "!contains(github.event.head_commit.message, 'Fixes coding style')"
        run: |
          pint

      # Step 8: Check for Changes After Pint
      - name: Check for Changes
        if: "!contains(github.event.head_commit.message, 'Fixes coding style')"
        id: changes
        run: |
          echo "::set-output name=changed::$(git status --porcelain)"

      # Step 9: Commit and Push Changes If Any
      - name: Commit and Push Changes
        if: steps.changes.outputs.changed != '' && !contains(github.event.head_commit.message, 'Fixes coding style')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fixes coding style"
          branch: main
          commit_author_name: github-actions
          commit_author_email: github-actions@github.com
